module "wrapper" {
  source = "../../modules/node-pool"

  for_each = var.items

  apiserver_private_host  = try(each.value.apiserver_private_host, var.defaults.apiserver_private_host, null)
  autoscale               = try(each.value.autoscale, var.defaults.autoscale, false)
  availability_domains    = try(each.value.availability_domains, var.defaults.availability_domains)
  boot_volume_size        = try(each.value.boot_volume_size, var.defaults.boot_volume_size, 50)
  capacity_reservation_id = try(each.value.capacity_reservation_id, var.defaults.capacity_reservation_id, null)
  cluster_id              = try(each.value.cluster_id, var.defaults.cluster_id)
  cluster_type            = try(each.value.cluster_type, var.defaults.cluster_type)
  cni_type                = try(each.value.cni_type, var.defaults.cni_type)
  compartment_id          = try(each.value.compartment_id, var.defaults.compartment_id)
  defined_tags            = try(each.value.defined_tags, var.defaults.defined_tags, {})
  eviction_grace_duration = try(each.value.eviction_grace_duration, var.defaults.eviction_grace_duration, 300)
  force_node_action       = try(each.value.force_node_action, var.defaults.force_node_action, false)
  force_node_delete       = try(each.value.force_node_delete, var.defaults.force_node_delete, false)
  freeform_tags           = try(each.value.freeform_tags, var.defaults.freeform_tags, {})
  image_id                = try(each.value.image_id, var.defaults.image_id)
  kubeproxy_mode          = try(each.value.kubeproxy_mode, var.defaults.kubeproxy_mode, "iptables")
  kubernetes_version      = try(each.value.kubernetes_version, var.defaults.kubernetes_version)
  max_pods_per_node       = try(each.value.max_pods_per_node, var.defaults.max_pods_per_node, 31)
  memory                  = try(each.value.memory, var.defaults.memory, 16)
  name                    = try(each.value.name, var.defaults.name)
  network_launch_type     = try(each.value.network_launch_type, var.defaults.network_launch_type, null)
  node_cycling            = try(each.value.node_cycling, var.defaults.node_cycling, {})
  node_labels             = try(each.value.node_labels, var.defaults.node_labels, {})
  node_metadata           = try(each.value.node_metadata, var.defaults.node_metadata, {})
  nsg_ids                 = try(each.value.nsg_ids, var.defaults.nsg_ids, [])
  ocpus                   = try(each.value.ocpus, var.defaults.ocpus, 2)
  placement_fds           = try(each.value.placement_fds, var.defaults.placement_fds, null)
  pod_nsg_ids             = try(each.value.pod_nsg_ids, var.defaults.pod_nsg_ids, [])
  pod_subnet_id           = try(each.value.pod_subnet_id, var.defaults.pod_subnet_id, null)
  preemptible_config      = try(each.value.preemptible_config, var.defaults.preemptible_config, {})
  pv_transit_encryption   = try(each.value.pv_transit_encryption, var.defaults.pv_transit_encryption, true)
  shape                   = try(each.value.shape, var.defaults.shape)
  size                    = try(each.value.size, var.defaults.size, 1)
  ssh_public_key          = try(each.value.ssh_public_key, var.defaults.ssh_public_key, null)
  subnet_id               = try(each.value.subnet_id, var.defaults.subnet_id)
  timeouts                = try(each.value.timeouts, var.defaults.timeouts, {})
  volume_kms_key_id       = try(each.value.volume_kms_key_id, var.defaults.volume_kms_key_id, null)
}
